export const prerender = false;

import type { APIRoute } from 'astro';
import { formatErrorMessage, createErrorResponse, extractGeminiText, getCORSHeaders, logError, validateAuth } from './utils';

export const OPTIONS: APIRoute = async ({ request }) => {
  return new Response(null, {
    status: 204,
    headers: getCORSHeaders(request)
  });
};

export const POST: APIRoute = async ({ request }) => {
  const corsHeaders = getCORSHeaders(request);

  // Validate authentication
  const auth = validateAuth(request);
  if (!auth.valid) {
    return createErrorResponse(auth.error || 'Unauthorized', 401, corsHeaders);
  }

  try {
    const { topic, angle, cluster } = await request.json();

    if (!topic || !angle || !cluster) {
      return createErrorResponse('Topic, angle, and cluster are required', 400, corsHeaders);
    }

    const apiKey = import.meta.env.GOOGLE_GENERATIVE_AI_API_KEY;

    if (!apiKey) {
      logError('generate-draft', 'Gemini API key is not configured');
      return createErrorResponse('Gemini API key is not configured', 500, corsHeaders);
    }

    const prompt = `Write a structured blog post for Indian Class 11-12 Commerce students.

Topic: ${topic}
Angle: ${angle}
Cluster: ${cluster}

Requirements:
- Clear introduction explaining relevance
- 4-6 sections with H2 headings
- Simple, accessible language
- At least one real-world Indian example
- Exam relevance noted where applicable
- Brief summary at end
- Do NOT include frontmatter

Output format: Return JSON with keys: title, description (1 sentence), body (markdown), tags (array of 3-5 strings).
Return JSON only.`;

    const response = await fetch(
      'https://generativelanguage.googleapis.com/v1beta/models/gemini-3-flash-preview:generateContent',
      {
        method: 'POST',
        headers: { 
          'Content-Type': 'application/json',
          'x-goog-api-key': apiKey
        },
        body: JSON.stringify({
          contents: [{ parts: [{ text: prompt }] }],
          generationConfig: {
            temperature: 0.4,
            responseMimeType: 'application/json',
          },
        }),
      }
    );

    if (!response.ok) {
      const errorText = await response.text();
      logError('generate-draft Gemini API Error', errorText, { status: response.status });
      return createErrorResponse(`Gemini API failed with status ${response.status}`, 502, corsHeaders);
    }

    const data = await response.json();
    const generatedText = extractGeminiText(data);

    if (!generatedText) {
      logError('generate-draft', 'No content generated', { data });
      return createErrorResponse('No content generated by AI', 502, corsHeaders);
    }

    try {
      const parsed = JSON.parse(generatedText);
      return new Response(JSON.stringify(parsed), {
        status: 200,
        headers: { 
          'Content-Type': 'application/json',
          ...corsHeaders
        },
      });
    } catch (parseError) {
      logError('generate-draft-parse', parseError, { generatedText });
      return createErrorResponse(`Invalid JSON from AI: ${formatErrorMessage(parseError)}`, 502, corsHeaders);
    }

  } catch (error) {
    logError('generate-draft-route', error);
    return createErrorResponse(`Internal server error: ${formatErrorMessage(error)}`, 500, corsHeaders);
  }
};
