export const prerender = false;

import type { APIRoute } from 'astro';
import { formatErrorMessage, createErrorResponse, extractGeminiText, getCORSHeaders, logError, validateAuth } from './utils';

export const OPTIONS: APIRoute = async ({ request }) => {
  return new Response(null, {
    status: 204,
    headers: getCORSHeaders(request)
  });
};

export const POST: APIRoute = async ({ request }) => {
  const corsHeaders = getCORSHeaders(request);

  // Validate authentication
  const auth = validateAuth(request);
  if (!auth.valid) {
    return createErrorResponse(auth.error || 'Unauthorized', 401, corsHeaders);
  }

  try {
    const { title, body } = await request.json();

    if (!title && !body) {
      return createErrorResponse('Title or body is required', 400, corsHeaders);
    }

    const apiKey = import.meta.env.GOOGLE_GENERATIVE_AI_API_KEY;

    if (!apiKey) {
      logError('seo-description', 'Gemini API key is not configured');
      return createErrorResponse('Gemini API key is not configured', 500, corsHeaders);
    }

    const prompt = `You are an expert SEO copywriter.
Write a compelling, concise meta description for this article.
It must be under 155 characters.
It should be engaging and encourage clicks.
Do not wrap it in quotes or introductory text.

Title: ${title}
Content:
${body?.substring(0, 2000) || ''}`;

    const response = await fetch(
      'https://generativelanguage.googleapis.com/v1beta/models/gemini-3-flash-preview:generateContent',
      {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'x-goog-api-key': apiKey
        },
        body: JSON.stringify({
          contents: [{ parts: [{ text: prompt }] }],
          generationConfig: {
            temperature: 0.1,
          },
        }),
      }
    );

    if (!response.ok) {
      const errorText = await response.text();
      logError('seo-description Gemini API Error', errorText, { status: response.status });
      return createErrorResponse(`Gemini API failed with status ${response.status}`, 502, corsHeaders);
    }

    const data = await response.json();
    const generatedText = extractGeminiText(data);

    if (!generatedText) {
      logError('seo-description', 'No content generated', { data });
      return createErrorResponse('No content generated by AI', 502, corsHeaders);
    }

    return new Response(JSON.stringify({ description: generatedText }), {
      status: 200,
      headers: { 
        'Content-Type': 'application/json',
        ...corsHeaders
      },
    });
  } catch (error) {
    logError('seo-description-route', error);
    return createErrorResponse(`Internal server error: ${formatErrorMessage(error)}`, 500, corsHeaders);
  }
};
